name: Docker CD

on:
  push:
    paths:
      - "**"
jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    env: 
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Package Registry
      uses: crazy-max/ghaction-docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        tags: docker.io/alan01252/open-vmdk:latest
        labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"
        push: true
        platforms: linux/amd64
        file: "Dockerfile"
